# Generated by Django 6.0.7 on 2026-07-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
