# Generated by Django 6.0.7 on 2026-07-29 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_receipt_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment'), ('full_payment', 'Full Payment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payments/%Y/%m/')),
                ('attachment_type', models.CharField(choices=[('cheque_image', 'Cheque Image'), ('payment_screenshot', 'Payment Screenshot'), ('receipt_image', 'Receipt Image'), ('other', 'Other')], max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payments.payment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
