# Generated by Django 6.0.7 on 2026-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_method_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment'), ('full_payment', 'Full Payment'), ('advance', 'Advance'), ('final_payment', 'Final Payment'), ('late_fee', 'Late Fee'), ('adjustment', 'Adjustment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
