# Generated by Django 6.0.7 on 2026-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('professional-blue', 'Professional Blue'), ('modern-green', 'Modern Green'), ('elegant-dark', 'Elegant Dark'), ('warm-earth', 'Warm Earth'), ('minimalist-purple', 'Minimalist Purple')], default='professional-blue', max_length=30),
        ),
    ]
