# Generated by Django 6.0.7 on 2026-08-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sales', 'Sales'), ('accounts', 'Accounts'), ('management', 'Management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sales', 'Sales'), ('accounts', 'Accounts'), ('management', 'Management')], default='sales', max_length=20),
        ),
    ]
