# Generated by Django 6.0.7 on 2026-08-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('hero', 'Hero Enquiry'), ('strip', 'Launch Strip'), ('newsletter', 'Newsletter Subscribe'), ('book_now', 'Book Now'), ('register_interest', 'Register Interest')], default='hero', max_length=20),
        ),
    ]
