# Generated by Django 6.0.7 on 2026-08-03 12:26

from django.db import migrations, models


def migrate_is_active(apps, schema_editor):
    Project = apps.get_model('properties', 'Project')
    for project in Project.objects.all():
        project.status = 'booking_open' if project.is_active else 'inactive'
        project.save(update_fields=['status'])


def reverse_migrate_status(apps, schema_editor):
    Project = apps.get_model('properties', 'Project')
    for project in Project.objects.all():
        project.is_active = project.status != 'inactive'
        project.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('booking_open', 'Booking Open'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='booking_open', max_length=30),
        ),
        migrations.RunPython(migrate_is_active, reverse_migrate_status),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
