# Generated by Django 6.0.7 on 2026-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_project_is_active_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Google Maps share link', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Google Maps latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Google Maps longitude coordinate', max_digits=10, null=True),
        ),
    ]
