# Generated by Django 6.0.7 on 2026-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_document_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('salaried', 'Salaried'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
