# Generated by Django 6.0.7 on 2026-08-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_occupation_customer_occupation_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=200)),
                ('nominee_cnic', models.CharField(blank=True, max_length=15)),
                ('nominee_phone', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Nominee',
                'verbose_name_plural': 'Customer Nominees',
            },
        ),
    ]
