# Generated by Django 6.0.7 on 2026-07-26 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("payment_plan", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "previous_payments_handling",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer to New Customer"),
                            ("refund", "Refund to Original Customer"),
                        ],
                        default="transfer",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CancellationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_days",
                    models.IntegerField(help_text="Days from booking date (inclusive)"),
                ),
                (
                    "to_days",
                    models.IntegerField(help_text="Days from booking date (inclusive)"),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("deduction_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["from_days"],
            },
        ),
        migrations.CreateModel(
            name="EarlySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_installments", models.PositiveIntegerField()),
                (
                    "total_remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("approved", models.BooleanField(default=False)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "late_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "payment_allocation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Audit trail of which payments covered this installment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_installments", models.PositiveIntegerField(default=12)),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "down_payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("start_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "due_day",
                    models.PositiveIntegerField(
                        default=1, help_text="Day of month for due date"
                    ),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                (
                    "total_late_fee_applied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_auto_processed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Installment Plans",
            },
        ),
        migrations.CreateModel(
            name="InstallmentPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_installments", models.PositiveIntegerField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "down_payment_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                ("has_balloon_payment", models.BooleanField(default=False)),
                (
                    "balloon_installment_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "balloon_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstallmentReschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_due_date", models.DateField()),
                ("new_due_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("financial_hardship", "Financial Hardship"),
                            ("system_error", "System Error"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rescheduled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_installment_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "new_installment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LateFeeConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("per_day", "Per Day Fixed"),
                            ("per_day_percentage", "Percentage Per Day"),
                            ("monthly_percentage", "Monthly Percentage"),
                            ("tiered", "Tiered"),
                        ],
                        default="per_day",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_late_fee_per_installment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_late_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("waiver_allowed", models.BooleanField(default=True)),
                ("tiered_rules", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming Due Reminder"),
                            ("overdue", "Overdue Reminder"),
                            ("grace_period", "Grace Period Ending"),
                            ("late_fee", "Late Fee Applied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_via",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email"), ("both", "Both")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("delivery_status", models.CharField(default="pending", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Converted to Booking"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "advance_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("walk_in", "Walk-In"),
                            ("referral", "Referral"),
                            ("agent", "Agent"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("possession_date", models.DateField(blank=True, null=True)),
                ("is_possession_taken", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
