# Generated by Django 6.0.7 on 2026-08-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('installment_reminders', models.BooleanField(default=True)),
                ('overdue_payments', models.BooleanField(default=True)),
                ('payment_confirmations', models.BooleanField(default=True)),
                ('booking_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_contact', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('notification_type', models.CharField(choices=[('installment_reminder', 'Installment Reminder'), ('overdue_payment', 'Overdue Payment'), ('payment_confirmation', 'Payment Confirmation'), ('receipt_notification', 'Receipt Notification'), ('booking_notification', 'Booking Notification'), ('booking_approval', 'Booking Approval'), ('general', 'General')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('related_customer_id', models.CharField(blank=True, max_length=20)),
                ('related_booking_id', models.CharField(blank=True, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'channel'], name='notificatio_status_d69daf_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_be328b_idx')],
            },
        ),
    ]
